### ISSUE TITLE
Add --no-exsync flag

### ISSUE THREAD

**Issue by nietaki** [CrowdHailer/raxx_kit#69]
Exsync is a great option for fast iteration and beginners, but it's not without faults and can lead to some weird problems during development of non-trivial apps.

The aim of this issue would be to have a flag for opting out of exsync when generating the project.

An alternative would be to only reload modules in the project that are safe to reload (router, controllers), but that might be harder to implement and come with assumptions of its own.

**Comment by nietaki** [comment]
Will be part of https://github.com/CrowdHailer/raxx_kit/pull/71

**Comment by CrowdHailer** [comment]
released https://hex.pm/packages/raxx_kit/0.8.0
