### ISSUE TITLE
Make `mix raxx.new` an alias to `mix raxx.kit` 

### ISSUE THREAD

**Issue by nietaki** [CrowdHailer/raxx_kit#76]

**Comment by CrowdHailer** [comment]
Depending on what happens with json version we might end up having two tasks `raxx.web` `raxx.api` I guess in such a case just alias `raxx.web` to `raxx.new`. I'm probably thinking too far ahead anyway

**Comment by CrowdHailer** [comment]
I added this commit https://github.com/CrowdHailer/raxx_kit/commit/b57ee260eb4ba2be8f3ef793e487376412eb4226

In the raxx_kit project directory `mix raxx.new` works however it does not appear to work when the archive is installed.

**Comment by CrowdHailer** [comment]
https://elixir-lang.slack.com/archives/C03EPRA3B/p1546791644685100

Maybe we just rename the task as new?
